# Generated by Django 5.2.3 on 2025-06-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_db',
            old_name='password',
            new_name='Phone_num',
        ),
    ]
