# Generated by Django 5.2.3 on 2025-06-15 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_course_grade_student_delete_users_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='courses_name',
            field=models.ManyToManyField(related_name='students', to='users.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('courses_no', models.IntegerField()),
                ('courses_name', models.ManyToManyField(related_name='teachers', to='users.course')),
            ],
        ),
    ]
