# Generated by Django 5.2.3 on 2025-06-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('Phone_num', models.IntegerField()),
                ('email', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=6)),
                ('birthday', models.DateField()),
            ],
        ),
    ]
