# Generated by Django 5.2.3 on 2025-06-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_db',
            name='Phone_num',
            field=models.BigIntegerField(),
        ),
    ]
